### ISSUE TITLE
Lockscreen not displaying quotes on LineageOS

### ISSUE THREAD

**Issue by k2helix** [Yubyf/QuoteLock#15]
I just installed this module and nothing seems to happen on my lockscreen. Tried restarting SystemUI and rebooting but nothing happens. 

LSPosed logs say Loading module com.yubyf.quotelockx from /data/... and it is enabled for SystemUI

Android version: 12L

LSPosed version: 1.8.6

QuoteLockX version: latest

**Comment by k2helix** [comment]
Nevermind it was because there were no notifications

**Comment by Yubyf** [comment]
@k2helix Thank you for bringing this issue to our attention. We have identified that the module cannot be displayed on the lock screen of Android 12 and above when there are no notification messages. This is because the lock screen displays a full-screen clock interface when there are no notifications, and forcing the module to display in this interface would result in an unsightly appearance.

We apologize for any inconvenience this may have caused. However, we believe that it is important to prioritize the user experience and ensure that the lock screen remains elegant and easy to use. Therefore, we have decided not to display the module in the absence of notification messages.

Thank you for your understanding and please let us know if you have any further questions or concerns.

**Comment by k2helix** [comment]
Thanks for your response. It is understandable as the lock screen would look strange if quotes were displayed even when there are no notifications. It is the right decision to leave it as it is right now.
