### ISSUE TITLE
Nothing Phone - Theme issue

### ISSUE THREAD

**Issue by Thefreestyler** [Yubyf/QuoteLock#16]
When installed on the Nothing Phone (1) A063, running Android 13, the theme colors jump to default after a reboot.
After uninstalling QuoteLockX, theme colors remain as selected, also after a reboot.
Otherwise it works fine, as expected, just figured it would be worthy to mention for a bug fix or future update.

**Comment by Yubyf** [comment]
Thank you for your feedback! I have successfully reproduced the issue and plan to fix it in the next version. We look forward to any further feedback and suggestions you may have.

**Comment by Thefreestyler** [comment]
I will test the fix when the update is available, but kudos for finding that it was related to the dark mode settings. I would have never thought of the relation of the system theme, auto adjusting to dark mode settings.

**Comment by Yubyf** [comment]
It seems that I may have misunderstood your issue initially. I have now understood that the issue I've reproduced is that the app's theme does not take effect after restarting.

Upon further evaluation of your description, it appears that the issue could be due to the app's theme adjustments affecting the system's theme settings. Please confirm if this is indeed the case.
